[phases.setup]
nixPkgs = ["nodejs", "npm", "php81", "php81Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "./start.sh"
