[phases.setup]
nixPkgs = ["nodejs", "npm", "php81", "php81Packages.composer"]

[phases.install]
cmds = [
    "cp .env.example .env",
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php artisan key:generate --force && php artisan migrate --force && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
