services:
  - type: web
    name: diario-bordo
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader && npm ci && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan key:generate --force && php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: Diario de Bordo
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:VIyMbbpCg8fKf+UZC38JkRPbhShiek0WEUt64n15sf4=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d20oamumcj7s73dvka60-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: diario_bordo
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: Xpg13oq8Oqv1Uggu1nvxS53xQRHfyOJJ
      - key: LOG_LEVEL
        value: error
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
